#!/bin/sh

if [ "$#" -ne 1 ]; then
  echo "usage: $0 include/syscall.h" >&2
  exit 2
fi

awk '
  BEGIN {
    print "# generated by gen_usys.sh - do not edit"
    print "#include \"syscall.h\""
    print ""
  }

  /^#define[[:space:]]+SYS_[[:alnum:]_]+[[:space:]]+[0-9]+/ {
    symbol = $2
    sub(/^SYS_/, "", symbol)
    syscalls[$3] = symbol
  }

  END {
    for (i = 1; i in syscalls; i++) {
      symbol = syscalls[i]
      name = symbol == "sbrk" ? "sys_sbrk" : symbol

      print ".global " name
      print name ":"
      print " li a7, SYS_" symbol
      print " ecall"
      print " ret"
    }
  }
' "$1"
